version: '3.1'

services: 

  postgres:
    container_name:  postgres
    image:           postgres
    restart: "on-failure"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env


  redis:
    container_name:   redis
    image: redis
    restart: "on-failure"
    ports:
      - 6379:6379